apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gateway-app
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
      - env:
        - name: ATTACKED_HOST
          value: http://192.10.24.4:31189
        image: 192.10.24.21:80/library/micronaut-api:script
        imagePullPolicy: Always
        name: gateway-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-app
spec:
  type: NodePort
  selector:
    app: gateway-app
  ports:
    - port: 8585
      targetPort: 8080
